GET  http://localhost/api/translations

###
POST  http://localhost/api/translations/
content-type: application/json

{ "english": "Couch", "finnish": "Sohva" }
###
PATCH  http://localhost/api/translations/2
content-type: application/json

{ "english": "Couch Test", "finnish": "Sohva Testi" }